### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by RaghavAwasthi**

### CODE REVIEW

**Comment by RaghavAwasthi** [comment]
Sir please Merge this pr

**Comment by shubhamvashisht** [comment]
@RaghavAwasthi  Squash your commits into a single commit.

**Comment by shubhamvashisht** [comment]
@RaghavAwasthi Why did you edit readme file? The task was about writing sample tests only.

**Comment by RaghavAwasthi** [comment]
Sir I had Edited the readme file for a previous task

**Comment by RaghavAwasthi** [comment]
Sir i have squashed all the commits please merge it now

**Comment by RaghavAwasthi** [comment]
Sir Please Merge it now @shubhamvashisht

**Comment by shubhamvashisht** [comment]
@RaghavAwasthi  This task only requires writing tests. Only 2nd commit will be merged, Please undo 1st commit.

**Comment by RaghavAwasthi** [comment]
but sir what about   the previous task

**Comment by shubhamvashisht** [comment]
Link of your previous task instance?

**Comment by RaghavAwasthi** [comment]
Sir the link for previous task instance is https://codein.withgoogle.com/dashboard/task-instances/5763337189064704/

**Comment by RaghavAwasthi** [comment]
Please see to it @shubhamvashisht

**Comment by neelanshsahai** [comment]
@RaghavAwasthi I see that the task related to the documentation part is already approved.
Also I guess, you did the changes of this task in the same branch and pushed it.
As said by @m-murad it is suggested that you create another pull request from another branch for this task i.e. f818a3b65cddb314cc359d17da26309a44adc099, and limit this PR only to  9a0172dd131a4e41879cff16e615c1399251424f, because you have already referred to this PR in another task. :blush: .
If you have any further queries, you can ask me :+1:

**Comment by RaghavAwasthi** [comment]
I need your help  @neelanshsahai

**Comment by RaghavAwasthi** [comment]
I created another branch for the task but ended up with same commit copying to the other branch also how do i fix that

**Comment by neelanshsahai** [comment]
PM me on gitter :blush:

**Comment by RaghavAwasthi** [comment]
where i didnt get gitter

**Comment by RaghavAwasthi** [comment]
What is your username on gitter

**Comment by SachinRammoorthy** [comment]
@RaghavAwasthi see comment on the other PR. For future reference, try to create a new branch for all tasks, before you make changes.

**Pull request merged**
