### PR TITLE
Junittesttask

### PR DESCRIPTION
**Pull request by RaghavAwasthi**
Sir i have done the task please merge it now

### CODE REVIEW

**Comment by SachinRammoorthy** [comment]
@RaghavAwasthi I noticed your previous PR and difficulty in removing a commit. Hopefully, this will help:
Execute
`git checkout junittesttask` 
after that, to undo your commit, do `git rebase -i HEAD~2` and then replace `pick` with `drop` for the commit you want to undo (in this case, `Updated README file`).
After that, you should be good to go.
Let me know if you need more help

**Comment by RaghavAwasthi** [comment]
@SachinRammoorthy  Sir I ran into an error 
ice_screenshot_20171229-162352

**Comment by RaghavAwasthi** [comment]
sir should i execute `git push -f`

**Comment by SachinRammoorthy** [comment]
@RaghavAwasthi First of all, I am not a mentor! You do not need to call me sir.

Oops sorry forgot to mention previously. You will have to force push, i.e, `git push origin +junittesttask`

**Comment by RaghavAwasthi** [comment]
Its ok thanks alot Please merge it now

**Comment by SachinRammoorthy** [comment]
Glad I could be of help. 
But again, I am not a mentor. Just a fellow participant. A mentor will have a look at it and merge it soon enough.

**Comment by shubhamvashisht** [comment]
@RaghavAwasthi Looks good now. Good work and i hope you learned a lot from it.
@SachinRammoorthy  Appreciate you for helping fellow student.

**Pull request merged**
