### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by HussainArif12**

### CODE REVIEW

**Comment by SachinRammoorthy** [comment]
@HussainArif12 I think 1 test file is sufficient. Also, the build is failing because you have not imported `Assert` correctly. You can refer the other test files for correcting this.

**Comment by HussainArif12** [comment]
Okay I've sent my links on the comment area of the Google Code-In. Please check it out

**Comment by SachinRammoorthy** [comment]
@HussainArif12 I am not a mentor. Just a fellow participant.

**Comment by HussainArif12** [comment]
My other test file, is it correct though?

**Comment by SachinRammoorthy** [comment]
I am sorry. I cannot tell for sure. You could remove the first file and then see if the Travis build fails. That will tell you whether it is alright.

**Comment by HussainArif12** [comment]
I'm new to github. How can I remove my first test file?

**Comment by SachinRammoorthy** [comment]
`git rm <my-file>
git commit -m "Commit message"`

Be careful though - this will remove the file from the repo and your computer. If you think you may need it, make a copy of it.

**Comment by HussainArif12** [comment]
You're seriously a mentor now. Thank you Sir!

**Comment by SachinRammoorthy** [comment]
Haha 😄  thanks for that! Glad to be of help. And please don't call me Sir! 😅

**Pull request closed without merging**
