### PR TITLE
Added Test Cases 

### PR DESCRIPTION
**Pull request by divyanshkul**
GCI Task by Divyansh Kulshreshtha for the Jboss Community.

### CODE REVIEW

**Comment by divyanshkul** [comment]
@garg-anuj added a new class with the name divyanshApplicationTest.

**Comment by garg-anuj** [comment]
https://travis-ci.org/jboss-outreach/junit-get-started/builds/311138977#L488

**Comment by garg-anuj** [comment]
Your Array test have some issues

**Comment by divyanshkul** [comment]
Done! Thanks for your help @garg-anuj :)

**Comment by garg-anuj** [comment]
@divyanshkul Its important to start class name with Caps. Made that change for you :)

Thanks for your work

**Pull request merged**
