### PR TITLE
Added JUnit Test HussainsTest3.java

### PR DESCRIPTION
**Pull request by HussainArif12**
This code has assertTrue, assertFalse and other changes that are in the JUnit testing library

### CODE REVIEW

**Comment by HussainArif12** [comment]
New commit

**Comment by HussainArif12** [comment]
Finally!
Sorry for being a nuisance, mentor. Thanks for the help

**Comment by HussainArif12** [comment]
Added Newline

**Comment by shubhamvashisht** [comment]
@HussainArif12 Fine, good work. Just one more thing, squash your commits and then we are good to go.

**Pull request closed without merging**
